{
 "title": "Cluster Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Core", "type": "text", "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 }, "options": { "content": "# 컴포넌트\n\n핵심 구성요소" } },
  {
   "title": "Cluster",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Namespace",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{phase=\"Active\"})",
     "legendFormat": "활성"
    },
    {
     "expr": "count(kube_namespace_status_phase)",
     "legendFormat": "전체"
    }
   ]
  },
  {
   "title": "Service",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_service_info)", "legendFormat": "활성" },
    { "expr": "count(kube_service_info)", "legendFormat": "전체" }
   ]
  },
  {
   "title": "Pod",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_status_ready)", "legendFormat": "활성" },
    { "expr": "count(kube_pod_info)", "legendFormat": "전체" }
   ]
  },
  {
   "title": "Node",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSet",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_daemonset_status_number_ready)",
     "legendFormat": "활성"
    },
    { "expr": "count(kube_daemonset_created)", "legendFormat": "전체" }
   ]
  },
  {
   "title": "Deployment",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_condition{condition=\"Available\"})",
     "legendFormat": "활성"
    },
    { "expr": "count(kube_deployment_created)", "legendFormat": "전체" }
   ]
  },
  {
   "title": "StatefulSet",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_status_replicas_ready > 0)",
     "legendFormat": "활성"
    },
    {
     "expr": "count(kube_statefulset_created)",
     "legendFormat": "전체"
    }
   ]
  },
  {
   "title": "CronJob ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_cronjob_status_active)",
     "legendFormat": "활성"
    },
    { "expr": "count(kube_cronjob_info)", "legendFormat": "전체" }
   ]
  },
  { "title": "Events", "type": "text", "gridPos": { "h": 16, "w": 10, "x": 0, "y": 10 }, "options": { "content": "# 이벤트\n\nkube-event-exporter\n" } },
  { "title": "Security", "type": "text", "gridPos": { "h": 16, "w": 14, "x": 10, "y": 10 }, "options": { "content": "# 취약점\n\nkube-bench\n" } }
 ]
}