{
 "title": "Node Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "노드 수",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kubernetes-nodes\"}) or vector(0)",
     "legendFormat": "total count"
    }
   ]
  },
  {
   "title": "vCPU 수량",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM 총량",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "디스크",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 업타임",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(up{job=\"kubernetes-nodes\"}[5m]) / count_over_time(up{job=\"kubernetes-nodes\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "시간대 CPU 사용율",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1\n  - avg by(node)\n   (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "시간대별 MEM 사용율",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1\n  - (\n    (\n      node_memory_MemAvailable_bytes\n    ) / node_memory_MemTotal_bytes\n  )\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(\n  1\n  - (\n    (\n      node_memory_MemFree_bytes\n      + node_memory_Cached_bytes\n      + node_memory_Buffers_bytes\n    ) / node_memory_MemTotal_bytes\n  )\n)",
     "legendFormat": "{{node}}: wrong"
    }
   ]
  },
  {
   "title": "시간대별 DIsk 사용율",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (node) (\n  1 - (\n    node_filesystem_avail_bytes{mountpoint=\"/\"}\n    / node_filesystem_size_bytes{mountpoint=\"/\"}\n  ) \n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드별 네트워크 수신 (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node, group) (\n  label_replace(\n    rate(\n      node_network_receive_bytes_total{\n        device=~\"wlo.*|en.*|eth.*|ens.*|enp.*\"\n      }[1m]\n    ),\n    'group',\n    'external',\n    'device',\n    '.*'\n  ) or\n  label_replace(\n    rate(\n      node_network_receive_bytes_total{\n        device=~\"docker.*|cni.*|veth.*|flannel.*|br-.*|lo\"\n      }[1m]\n    ),\n    'group',\n    'internal',\n    'device',\n    '.*'\n  ) or\n  label_replace(\n    rate(\n      node_network_receive_bytes_total{\n        device!~\"wlo.*|en.*|eth.*|ens.*|enp.*|docker.*|cni.*|veth.*|flannel.*|br-.*|lo\"\n      }[1m]\n    ),\n    'group',\n    'unkown',\n    'device',\n    '.*'\n  )\n)",
     "legendFormat": "{{node}} - {{group}}"
    }
   ]
  },
  {
   "title": "노드별 네트워크 송신 (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node, group) (\n  label_replace(\n    rate(\n      node_network_transmit_bytes_total{\n        device=~\"wlo.*|en.*|eth.*|ens.*|enp.*\"\n      }[1m]\n    ),\n    'group',\n    'external',\n    'device',\n    '.*'\n  ) or\n  label_replace(\n    rate(\n      node_network_transmit_bytes_total{\n        device=~\"docker.*|cni.*|veth.*|flannel.*|br-.*|lo\"\n      }[1m]\n    ),\n    'group',\n    'internal',\n    'device',\n    '.*'\n  ) or\n  label_replace(\n    rate(\n      node_network_transmit_bytes_total{\n        device!~\"wlo.*|en.*|eth.*|ens.*|enp.*|docker.*|cni.*|veth.*|flannel.*|br-.*|lo\"\n      }[1m]\n    ),\n    'group',\n    'unkown',\n    'device',\n    '.*'\n  )\n)",
     "legendFormat": "{{node}}: {{group}}"
    }
   ]
  },
  {
   "title": "노드별 디스크 조회시간 (ms/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(node) (\n  rate(node_disk_read_time_seconds_total[5m]) / \n  clamp_min(rate(node_disk_reads_completed_total[5m]), 0.001)\n) * 1000\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드별 디스크 쓰기시간 (ms/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(node) (\n  rate(node_disk_write_time_seconds_total[5m]) / \n  clamp_min(rate(node_disk_writes_completed_total[5m]), 0.001)\n) * 1000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드별 디스크 조회 (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  rate(node_disk_read_bytes_total[5m])\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드별 디스크 쓰기 (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  rate(node_disk_written_bytes_total[5m])\n)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}