---
apiVersion: v1
kind: Service
metadata:
  name: hpa-01-basic
  labels:
    app: hpa-01-basic
spec:
  selector:
    app: hpa-01-basic
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-01-basic
  labels:
    app: hpa-01-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpa-01-basic
  template:
    metadata:
      labels:
        app: hpa-01-basic
    spec:
      containers:
      - name: hpa-01-basic
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-01-basic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-01-basic
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70